language: go

go:
    - "1.8.3"

services:
    - docker

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - docker build -t proxyfs test/container
    - container_id=$(mktemp)
    - echo ${container_id}
    - docker run -d --privileged -v `pwd`:/proxyfs --cidfile "${container_id}" proxyfs
    - cat ${container_id}

script:
    - docker exec -it `cat ${container_id}` bash -c 'ls -la /'
    - docker exec -it `cat ${container_id}` bash -c 'whoami'
    - docker exec -it `cat ${container_id}` bash -c 'pwd'
    - docker exec -it `cat ${container_id}` bash -c 'ls -la'
