services:
    - docker

language: go

go:
    - "1.8.3"

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - docker build -t proxyfs test/container
    - cidfile=$(mktemp -u)

install:
    - docker run -d -v `pwd`:/proxyfs --cidfile "${cidfile}" -w /proxyfs proxyfs ls -la

#script:
#    - docker exec -it `cat ${cidfile}` bash -c 'ls -la /'
#    - docker exec -it `cat ${cidfile}` bash -c 'whoami'
#    - docker exec -it `cat ${cidfile}` bash -c 'pwd'
#    - docker exec -it `cat ${cidfile}` bash -c 'ls -la'
